name: Staging Pipeline

on:
  pull_request:
    branches:
      - staging
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Add steps to build and test the code
      run: |
        echo "Running staging pipeline"

  merge_to_master:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to merge code to master branch
        run: |
          echo "Staging is approved and merge code to master branch"
