name: Workflow on Staging Merge

on:
  push:
    branches:
      - staging

jobs:
  check_staging_merge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Check if staging is merged into master
        id: check_merge
        run: |
          if git branch --contains staging | grep -q master; then
            echo "::set-output name=merged::true"
          else
            echo "::set-output name=merged::false"
          fi

  manual_trigger:
    needs: check_staging_merge
    runs-on: ubuntu-latest
    if: needs.check_staging_merge.outputs.merged == 'true'

    steps:
      - name: Manually trigger workflow with inputs
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/NAME_OF_YOUR_WORKFLOW/dispatches \
            -d '{"ref":"main", "inputs":{"input_name":"input_value"}}'
