name: PUSH Staging Pipeline

on:
  push:
    branches:
      - staging
      - master

jobs:
  staging-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Add steps to build and test the code
      - name: Build and test
        run: |
          echo "PUSH - Running staging pipeline"

      # After successful testing, create a pull request to merge staging into master
  # After successful testing, create a pull request to merge staging into master
  check_staging_merge:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'

    steps:
      - name: Check if staging is merged into master
        id: check_merge
        run: |
          if git branch --contains staging | grep -q master; then
            echo "::set-output name=merged::true"
          else
            echo "::set-output name=merged::false"
          fi


  manual_trigger:
    needs: check_staging_merge
    runs-on: ubuntu-latest
    if: needs.check_staging_merge.outputs.merged == 'true'

    steps:
      - name: Manually trigger workflow with inputs
        run: |
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/pr-staging-pipeline.yml/dispatches \
          -d '{"ref":"main"}'



        

