name: PUSH - Staging Pipeline

on: 
  push:
    branches:
      - staging

jobs:
  push-staging-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Add steps to build and test the code
      - name: Build and test
        run: |
          echo "PUSH - Running staging pipeline"

  merge_to_master:
    needs: push-staging-pipeline
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Add steps to merge code to master branch
      - name: Merge to master
        run: |
          # Placeholder for merging code to master
          echo "Staging is approved and merged , now this code can be merged to master branch"

